OnlineShop/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineShop.Models;

namespace OnlineShop.Controllers
{
    public class CartController : Controller
    {
        private readonly OnlineShopeEntity onlineShope;
        private readonly UserManager<User> userManager;
        public CartController( OnlineShopeEntity _onlineShope,UserManager<User> _userManager)
        {
            onlineShope = _onlineShope;
            userManager= _userManager;
        }
        
           [Authorize]
        public IActionResult ItemInCart()
        {
            string IdUser = userManager.GetUserId(User);
            Cart MyCart = onlineShope.Carts.Include(i => i.CartProducts).FirstOrDefault(a => a.UserId == IdUser);
            foreach (CartProduct p in MyCart.CartProducts)
           {
               var prod = onlineShope.Products.Include(q=>q.category).Include(e=>e.ProductImagsss).FirstOrDefault(i => i.Id == p.ProductId);
               p.product = prod;
           }

            return View(MyCart);
        }
        public IActionResult DeleteFromCart(int id)
        {
            string IdUser = userManager.GetUserId(User);
            Cart MyCar = onlineShope.Carts.Include(i => i.CartProducts).FirstOrDefault(a => a.UserId == IdUser);
            foreach (CartProduct p in MyCar.CartProducts)
            {
                var prod = onlineShope.Products.Include(q => q.category).FirstOrDefault(i => i.Id == p.ProductId);
                p.product = prod;
            }
            foreach (CartProduct p in MyCar.CartProducts)
            {

                if (p.ProductId == id)
                {
                    if (p.Quantity == 1)
                    {
                        MyCar.CartProducts.Remove(p);
                        MyCar.TotalPrice = MyCar.TotalPrice - p.product.ProPrice;
                        MyCar.totalQuantity--;
                        break;
                    }
                    else
                    {
                        p.Quantity--;
                        MyCar.TotalPrice = MyCar.TotalPrice - p.product.ProPrice;
                        MyCar.totalQuantity--;
                        break;
                    }
                }

            }      
            onlineShope.Carts.Update(MyCar);
            onlineShope.SaveChanges();

            return RedirectToAction("ItemInCart");
        }

        public IActionResult IncreadeToCart(int id)
        {
            string IdUser = userManager.GetUserId(User);
            Cart MyCa = onlineShope.Carts.Include(i => i.CartProducts).FirstOrDefault(a => a.UserId == IdUser);
            foreach (CartProduct p in MyCa.CartProducts)
            {
                var prod = onlineShope.Products.Include(q => q.category).FirstOrDefault(i => i.Id == p.ProductId);
                p.product = prod;
            }
            foreach(CartProduct pc in MyCa.CartProducts)
            {
                if(pc.ProductId == id)
                {
                    pc.Quantity++;
                    MyCa.TotalPrice = MyCa.TotalPrice + pc.product.ProPrice;
                    MyCa.totalQuantity++;
                    break;
                }
            }
            onlineShope.Carts.Update(MyCa);
            onlineShope.SaveChanges();
            return RedirectToAction("ItemInCart");
        }
    }
}

OnlineShop/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineShop.Models;
using OnlineShop.ViewModel;

namespace OnlineShop.Controllers
{
    public class OrderController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly OnlineShopeEntity onlineShope;
        public OrderController(OnlineShopeEntity _onlineShope,UserManager<User> _userManager)
        {
            onlineShope = _onlineShope;
            userManager = _userManager;
        }
        [HttpGet]
        [Authorize]
        public IActionResult MakeOrder()
        {
            return View();
        }
        [HttpPost]
        [Authorize]
        public IActionResult MakeOrder(AddOrderViewModel addOrder)
        {
            string IdUser = userManager.GetUserId(User);
            Cart MyCart = onlineShope.Carts.Include(i => i.CartProducts).FirstOrDefault(a => a.UserId == IdUser);

            if (ModelState.IsValid == false)
            {
                return View();
            }
            else
            {
                var ord = new Order();
                ord.Address = addOrder.Address;
                ord.Email = addOrder.Email;
                ord.PhoneNumber = addOrder.PhoneNumber;
                ord.OrderDate = DateTime.Now;
                ord.Name = addOrder.Name;
                
                onlineShope.Orders.Add(ord);
                onlineShope.SaveChanges();
                var orderss = onlineShope.Orders.Include(q => q.OrderProducts).FirstOrDefault(w => w.Id == ord.Id);
                foreach (CartProduct p in MyCart.CartProducts)
                {

                    orderss.OrderProducts.Add(new OrderProduct { OrderId = ord.Id, ProductId = p.ProductId,Quantity=p.Quantity });
                    //onlineShope.CartProducts.Remove(p);
                    //onlineShope.SaveChanges();
                    
                }
                onlineShope.Orders.Update(orderss);
                onlineShope.SaveChanges();

                //foreach(CartProduct c in MyCart.CartProducts)
                //{
                // MyCart.CartProducts.Remove(c);
                // }

               // for (int i = 0; i < MyCart.CartProducts.Count; i++)
                //{

                // MyCart.CartProducts.RemoveAt(i);

                //}

               // onlineShope.Carts.Update(MyCart);
               // onlineShope.SaveChanges();

                return RedirectToAction("Index", "Home");
            }

            

        }
        [Authorize]
       public IActionResult GetAllOrders()
        {
            IEnumerable<Order> ord = onlineShope.Orders.Include(q => q.OrderProducts).ToList();
            foreach(Order ou in ord)
            {
                foreach(OrderProduct orderProduct in ou.OrderProducts)
                {
                    product rpo = onlineShope.Products.Include(e=>e.category).FirstOrDefault(q => q.Id == orderProduct.ProductId);
                    orderProduct.product = rpo;
                }
            }
            return View(ord);
        }
        [Authorize(Roles ="admin")]
        public IActionResult DeleteOrder(int id)
        {
            var ordd=onlineShope.Orders.FirstOrDefault(q=>q.Id == id); 
            onlineShope.Orders.Remove(ordd);
            onlineShope.SaveChanges();
            return RedirectToAction("GetAllOrders");
        }
    }
}

OnlineShop/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.ViewModel;

namespace OnlineShop.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> RoleManager;
        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            RoleManager = roleManager;
        }
        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult AddRole()
        {
            return View();
        }
        
            [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> AddRole(AddRoleViewModel model)
        {
            if (!ModelState.IsValid)
                return View();
            else
            {
                var result =
                await RoleManager.CreateAsync(new IdentityRole()
                {
                    Name = model.Name
                });
                if (!result.Succeeded)
                {
                    result.Errors.ToList().ForEach(i =>
                    {
                        ModelState.AddModelError("", i.Description);
                    });
                    return View();
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
        }
    }
}

OnlineShop/Controllers/UserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OnlineShop.Models;
using OnlineShop.ViewModel;

namespace OnlineShop.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly SignInManager<User> signInManager;
        private readonly OnlineShopeEntity onlineShopeEntity;
        private readonly RoleManager<IdentityRole> RoleManager;
        public UserController(UserManager<User> _userManager, SignInManager<User> _signInManager,RoleManager<IdentityRole> roleManager ,OnlineShopeEntity _onlineShopeEntity)
        {
            userManager = _userManager;
            signInManager = _signInManager;
            RoleManager = roleManager;
            onlineShopeEntity = _onlineShopeEntity;

        }
        [HttpGet]
        public IActionResult Register()
        {
           // ViewBag.Roles = RoleManager.Roles.ToList().Select(i => new SelectListItem(i.Name, i.Name)).ToList();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(AddUserViewModel addUser)
        {
            

            if (ModelState.IsValid == false)
            {
                return View();
            }
            else
            {
                User user = new User();
                user.UserName = addUser.UserName;
                user.Email = addUser.Email;
                user.firstName = addUser.FirstName;
                user.lastName = addUser.LastName;
                IdentityResult result =
                    await userManager.CreateAsync(user, addUser.Password);
                   // await userManager.AddToRoleAsync(user, addUser.Role);
                if (result.Succeeded == false)
                {
                    result.Errors.ToList().ForEach(

                        i =>
                        {
                            ModelState.AddModelError("", i.Description);
                        }

                        );
                    return View();
                }
                else
                {
                    Cart cart = new Cart();
                    cart.totalQuantity = 0;
                    cart.TotalPrice = 0;
                    cart.UserId=user.Id;
                    onlineShopeEntity.Carts.Add(cart);
                    Favourite favourite = new Favourite();
                    favourite.UserId=user.Id;
                    onlineShopeEntity.Favorites.Add(favourite);
                    onlineShopeEntity.SaveChanges();
                    return RedirectToAction("Get", "Product");
                }

            }
        }

        public async Task<IActionResult> SignIn()
        {
            return View();
        }
        [HttpPost]
            public async Task<IActionResult> SignIn(SignInModel model)
        {
            if (ModelState.IsValid == false)
            {
                return View();
            }
            else
            {

                var result = await signInManager.PasswordSignInAsync(model.UserName, model.Password, model.RememberMe, false);
                if (result.Succeeded == false)
                {
                    ModelState.AddModelError("", "This Passwoed or User Name is incorect");
                    return View();
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }

            }
        }

        public async Task<IActionResult> SignOut()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    } 
}

OnlineShop/Views/Shared/_Layout.cshtml
@inject SignInManager<User> signInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] OnlineShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlineShop.styles.css" asp-append-version="true" />
    
</head>
<body>
    <header> 
        @if(User.IsInRole("admin"))
        {
            <div class="d-flex justify-content-between border-bottom shadow-sm mb-5 p-1 ps-5 pe-5 bg-white rounded fs-5 fw-bold fst-italic">
                    <div>
                        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light ">
                            <ul class="navbar-nav ">
                                <li class="nav-item">
                                    <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index"> OnlineShop </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                  <div>
                      <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light ">
                          <ul class="navbar-nav ">

                           
                              <li class="nav-item ps-5">
                               <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="GetAllOrders">Orders</a>

                               </li>
                           

                            <li class="nav-item ps-5">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Get">Product</a>
                            </li>

                            <li class="nav-item ps-5">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="AddRole">Role</a>
                            </li>

                        </ul>
                      
                    </nav>
                </div>
                <div>
                    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light ">
                        <ul class="navbar-nav flex-grow-1">
                           
                                <li class="nav-item ">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="SignOut">SignOut </a>
                                </li>
                        </ul>
                    </nav>
                </div>
            </div>

        }
         else
        {
        <div class="d-flex justify-content-between border-bottom shadow-sm mb-5 p-1 ps-5 pe-5 bg-white rounded fs-5 fw-bold fst-italic">
            <div>
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light ">
                    <ul class="navbar-nav ">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index"> OnlineShop </a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div>
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light ">
                    <ul class="navbar-nav ">

                        <li class="nav-item dropdown pe-5">
                            <a class="nav-link active dropdown-toggle" data-bs-toggle="dropdown">
                                Categores
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="Category" asp-action="GetLaptops">Laptop</a></li>
                                <li><a class="dropdown-item" asp-controller="Category" asp-action="GetPhones">Mobile Phone</a></li>
                                <li><a class="dropdown-item" asp-controller="Category" asp-action="GetSamrtTv">SmartTV</a></li>
                            </ul>
                        </li>

                        <li class="nav-item ps-4">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="ItemInCart"> MyCart </a>
                        </li>

                            <li class="nav-item ps-5">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="GetAllOrders">Orders</a>

                            </li>


                            @* <li class="nav-item ps-5">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Get">Product</a>
                        </li>*@
                       

                        <li class="nav-item ps-5">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Favourite" asp-action="FavouriteItem">Favourite Item</a>
                        </li>
                            @*<li class="nav-item ps-5">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="AddRole">Role</a>
                        </li>*@
                        
                    </ul>

                </nav>
            </div>
            <div>
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light ">
                    <ul class="navbar-nav flex-grow-1">
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item ">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="SignOut">SignOut </a>
                            </li>


                        }
                        else
                        {
                            <li class="nav-item pe-3">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Register"> Register </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="SignIn">SignIn </a>
                            </li>
                        }
                    </ul>
                </nav>
            </div>
        </div>
        }
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    
   
 
</body>
</html>